version: '3.1'

services:
  game-server:
    build:
      context: .
      dockerfile: build/Dockerfile
    container_name: game-server
    tty: true   # Pour laisser le container en marche

    volumes:
      - ./games:/var/www/html

    ports:
      - '8080:80'
